#:kivy {{cookiecutter.kivy_version}}

<Controller>:
    label_wid: my_custom_label

    BoxLayout:
        orientation: 'vertical'
        padding: 20

        Button:
            text: 'My App is: ' + root.info
            on_press: root.do_action()

        Label:
            id: my_custom_label
            text: 'My label before button press'

        Label:
            id: version
            text: '{{cookiecutter.app_title}}: {{cookiecutter.version}}'